# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
  end
  config.vm.provision "shell", path: 'ruby.sh', privileged: false
  config.vm.provision "shell", path: 'phantomjs.sh', privileged: true
  config.vm.provision "shell", path: 'nodejs.sh', privileged: false
  config.vm.provision "shell", path: 'npm_packages.sh', privileged: false

  config.vm.synced_folder ".", "/vagrant", :mount_options => ['dmode=774','fmode=775']
end
